#ifndef SUDOKUSOLVERCORE_GLOBAL_H
#define SUDOKUSOLVERCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SUDOKUSOLVERCORE_LIBRARY)
#  define SUDOKUSOLVERCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SUDOKUSOLVERCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SUDOKUSOLVERCORE_GLOBAL_H
